server:
  port: 8761
spring:
  application:
    name: eurekaserver
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
